[package]
name = "battle-city"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_rapier2d = "0.21.0"
bevy-inspector-egui = "0.18.3"
bevy_ecs_ldtk = "0.7.0"
rand = "0.8.5"

[dependencies.bevy]
version = "0.10.1"
features = [
    "bmp",
]